### ISSUE TITLE
Token present in source

### ISSUE THREAD

**Issue by bippum** [thomasbnt/bot-discord-basic-js#2]
You've used your token inside your source file. https://github.com/thomasbnt/bot-discord-basic-js/blob/master/bot.js#L43

A token should be kept private as this allows anyone to log in to the account of the bot. Here are some steps you should take:
 - Regen the token on https://discordapp.com/developers/applications/me
 - Move your token to a new file `token.json`
```json
{ "token": "your token" }
```
 - Replace the token in your source with a require statement for said other file `bot.run(require('./token.json').token)`

**Comment by thomasbnt** [comment]
Token invalid 🙊😉

**Comment by bippum** [comment]
It's still good practice to hide it in source.

**Comment by thomasbnt** [comment]
Okay  thx u 😉
